export const ideas = [
  {
    title: "Simple To-Do List",
    description: "Add, complete, and delete daily tasks.",
    difficulty: "easy",
    category: "frontend",
    coreSkills: ["html", "css", "javascript"],
    stretchSkills: ["localstorage"],
    steps: [
      "Create the basic HTML layout",
      "Style the layout with CSS",
      "Add JavaScript to create and delete tasks",
      "Add task completion toggle",
      "Save tasks using localStorage",
    ],
  },
  {
    title: "Digital Stopwatch",
    description: "A stopwatch with start, stop, and reset features.",
    difficulty: "easy",
    category: "frontend",
    coreSkills: ["html", "css", "javascript"],
    stretchSkills: ["animations"],
    steps: [
      "Design the stopwatch UI",
      "Implement the timer logic",
      "Add start and stop buttons",
      "Add reset functionality",
    ],
  },
  {
    title: "Random Quote Generator",
    description: "Displays random motivational quotes.",
    difficulty: "easy",
    category: "frontend",
    coreSkills: ["javascript"],
    stretchSkills: ["api"],
    steps: [
      "Create the page layout",
      "Store a list of quotes in JavaScript",
      "Display a random quote on button click",
      "Fetch quotes from an API (optional)",
    ],
  },
  {
    title: "Password Strength Checker",
    description: "Visualizes password strength in real time.",
    difficulty: "easy",
    category: "logic",
    coreSkills: ["javascript"],
    stretchSkills: ["regex"],
    steps: [
      "Build the password input UI",
      "Detect password length",
      "Check for numbers and symbols",
      "Show strength visually",
    ],
  },
  {
    title: "Notes App",
    description: "Create, edit, and delete personal notes.",
    difficulty: "medium",
    category: "frontend",
    coreSkills: ["react", "state"],
    stretchSkills: ["localstorage"],
    steps: [
      "Create note layout UI",
      "Add note creation logic",
      "Implement editing notes",
      "Add delete functionality",
      "Persist notes with localStorage",
    ],
  },
  {
    title: "Weather App",
    description: "Fetches live weather data by city name.",
    difficulty: "medium",
    category: "frontend",
    coreSkills: ["javascript", "api"],
    stretchSkills: ["geolocation"],
    steps: [
      "Create search input UI",
      "Fetch weather data from API",
      "Display temperature and conditions",
      "Handle loading and error states",
      "Add geolocation support",
    ],
  },
  {
    title: "Habit Tracker",
    description: "Tracks daily habits and visualizes progress.",
    difficulty: "medium",
    category: "fullstack",
    coreSkills: ["react", "state"],
    stretchSkills: ["charts"],
    steps: [
      "Build habit list UI",
      "Add habit creation",
      "Track completed habits",
      "Store progress locally",
      "Show simple charts",
    ],
  },
  {
    title: "Chat App",
    description: "Send real-time messages between users.",
    difficulty: "hard",
    category: "fullstack",
    coreSkills: ["react", "api", "auth"],
    stretchSkills: ["websockets"],
    steps: [
      "Design chat interface",
      "Build message input system",
      "Implement realtime updates",
      "Add user authentication",
      "Deploy the app",
    ],
  },
];
